### ISSUE TITLE
im a lil dumb 

### ISSUE THREAD

**Issue by owmywifi** [ZehsTeam/Lethal-Company-CoilHeadSettings#1]
how to i actually configure these settings?

**Comment by ZehsTeam** [comment]
@owmywifi 

## Thunderstore method (Recommended)
If you are using a mod manager like [Thunderstore](https://www.overwolf.com/app/Thunderstore-Thunderstore_Mod_Manager), you can easily edit the config settings.

<img src="https://i.imgur.com/augXrtG.png">

## Manual method
Another method is editing the config file itself by finding it using the file explorer.
The file location should be in somewhere like: `SteamLibrary\steamapps\common\Lethal Company\BepInEx\config`
Double-clicking the file should open it in notepad or any text editor of your choice. You can also right-click the file and open it with your program of choice.

<img src="https://i.imgur.com/eDK8tbS.png">

## Additional info
If you need additional help, you can ask in one of these Discord servers in the **CoilHeadSettings** posts.

| Discord server | Channel | Post |
| ----------- | ----------- | ----------- |
| [Lethal Company modding Discord](https://discord.gg/XeyYqRdRGC) | `#mod-releases` | [CoilHeadSettings](https://discord.com/channels/1168655651455639582/1213608309953929297) |
| [Unofficial Lethal Company Community](https://discord.gg/nYcQFEpXfU) | `#mod-releases` | [CoilHeadSettings](https://discord.com/channels/1169792572382773318/1213608502233268314) |
