### ISSUE TITLE
Coilhead can't attack me

### ISSUE THREAD

**Issue by habacksill** [ZehsTeam/Lethal-Company-CoilHeadSettings#2]
When I change the config of the coilhead coildhead can't attack me even the attack damage higher than 0.
does the coilhead can't attack me when it's speed is under default?(Default is 14.5 and mine is 6)

**Comment by ZehsTeam** [comment]
@habacksill This has been fixed in the latest version [v2.0.0+](https://thunderstore.io/c/lethal-company/p/Zehs/CoilHeadSettings/) [2305715](https://github.com/ZehsTeam/Lethal-Company-CoilHeadSettings/commit/2305715be17599eca0f4309bafbe2393529bb7fe)
